version: 2.1
jobs:
  foo:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

  bar:
    machine: true
    steps:
      - checkout
  lol:
    machine: true
    steps:
      - checkout
workflows:
  workflow:
    jobs:
      - foo
      - bar
      - lol
